{% set name = "napari-philow" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 73c9870e2fa7cb85ad3d2c8f658033ec57f149a4057e8fa67764d1bebac9b74c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dask
    - dask-image
    - matplotlib-base
    - napari
    - pyqt
    - numpy
    - opencv
    - pandas
    - python >={{ python_min }}
    - scikit-image
    - pytorch
    - torchvision
    - segmentation-models-pytorch

  run_constrained:
    - pyside2 >=5.14.2,!=5.15.0
    - pyqt >=5.12.3,!=5.15.0

test:
  imports:
    - napari_philow
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/neurobiology-ut/PHILOW
  summary: PHILOW is an interactive deep learning-based platform for 3D datasets
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hiroalchem
    - goanpeca
    - jaimergp
